name: Contract Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      build_path: '[""]'
      release_description: 'Release of the contract'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}